### ISSUE TITLE
Support Page, "Contact" Link defunct

### ISSUE THREAD

**Issue by AlbinoGeek** [fyne-io/apps.fyne.io#10]
Since `https://fyne.io/develop/` goes to `https://developer.fyne.io/` -- the second URL on the support page no longer functions.

Nor is there an anchor at the redirect destination for me to PR the change.

URL: `https://fyne.io/develop/#contact`

I'm not sure what this URL should be replaced with.

**Comment by andydotxyz** [comment]
Probably just #contact on the current page I think

**Comment by AlbinoGeek** [comment]
https://developer.fyne.io/#contact is a valid URL, but the fragment refers to an anchor that does not exist.
[ There's no `<a name="contact">` on the new URL. ]

**Comment by andydotxyz** [comment]
I thought you were referring to the support page on the Fyne website? 
If so then https://fyne.io/support/#contact would work.
