### ISSUE TITLE
Add an "Also on Flathub" page

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/apps.fyne.io#29]
We have "Also on Google Play" and "Also on Apply App Store". I think it would be great if we could have something similar now that rymdport (https://flathub.org/apps/details/io.github.jacalz.rymdport) is, and presumably more to follow, are on Flathub.

**Comment by andydotxyz** [comment]
Sure thing. Feel free to add!

**Comment by Jacalz** [comment]
I would if I knew anything about JavaScript, Jekyll or similar 😅

**Comment by Jacalz** [comment]
Thanks. Nice work 👍
