### ISSUE TITLE
app donation button on fyne.io

### ISSUE THREAD

**Issue by ghost** [fyne-io/apps.fyne.io#36]
Hi all. 

I wonder if you've all thought about adding a donate button to the site. *Would it be possible to have a donation button to encourage the development of fyne.io?* 

**Note:** They recommended talking about this idea here.

#### Idea
![image](https://user-images.githubusercontent.com/111701513/192289523-08ed869a-f437-4582-a297-161b97fd870a.png)

**Comment by andydotxyz** [comment]
That's a pretty cool idea.
Would each developer provide their own place for donations, or were you considering that it's for the toolkit overall?

**Comment by andydotxyz** [comment]
Sure thing, but to what benefactor? The developer or the library?

**Comment by andydotxyz** [comment]
Not sure this was completed?

**Comment by andydotxyz** [comment]
Yes thanks for the help, it is appreciated

> > Sure thing, but to what benefactor?
> 
> The developer and library.

But your example doesn't fit with what you said above?

**Comment by andydotxyz** [comment]
You previously said that donation links could be made to the developer and to the library didn't you?
I think the version you illustrated is just for app developers, so I was looking to clarify.

**Comment by andydotxyz** [comment]
Yes the code looks like a solid approach

**Comment by andydotxyz** [comment]
> _So can I close this issue? Is there anything that needs to be done or clarified?_

Well, you should not close an issue until it is resolved - that is a PR has landed that completes the work.

> From what I've researched in the apps.fyne.io repository works with jekyll through markdown.(Is this correct?)

Yes that is correct.

> I wanted to know if this information is correct, if there is any dependency on functioning.

An issue is not closed because code has been pasted, there would need to be a PR created, reviewed and landed.

> I imagined that adding just one line equal to home would generate an automatic link through the markdown property.

Yes I think that is correct
