### ISSUE TITLE
apps.fyne.io in fyne.io/apps

### ISSUE THREAD

**Issue by ghost** [fyne-io/apps.fyne.io#41]
Hi all.

I would like to know if you have already thought about adding the url: 'apps.fyne.io' in the main url 'fyne.io/apps'.

*What do you all think of this idea?*

**Comment by andydotxyz** [comment]
I'm not sure I understand the question. If you go to https://fyne.io/apps/ it redirects to the dedicated site https://apps.fyne.io.
What is your suggestion?

**Comment by andydotxyz** [comment]
Why would this be beneficial?
Personally I don't like it when sites change their look and navigation when you go to a subdirectory...
