### ISSUE TITLE
homepage with slideshow

### ISSUE THREAD

**Issue by ghost** [fyne-io/apps.fyne.io#42]
Hi everyone.

I would like to know what you all think about the idea of ​​having a slide on the apps.fyne.io page. My idea is that each developer includes the app's interface before installing. Thus, it is easier for the user to be aware of what can happen when installing.

#### Concept
![](https://csshint.com/wp-content/uploads/2020/08/Simple-Bootstrap-Carousel.gif)

What do you all think of this idea? Is it possible to have this image slide feature on apps.fyne.io?

*I noticed that the design had changed after the pull request. So the design is incredible.*

**Comment by Jacalz** [comment]
I think this is a very good idea. We could do this like in Gnome Software where a colour is used behind the icon:
![image](https://user-images.githubusercontent.com/25466657/204629420-0b640f87-24c4-434e-acf2-1d352f68d7c3.png)
This avoids the need for banner images and clearly displays applications in a neat way.

**Comment by andydotxyz** [comment]
Pushed a simple implementation that allows both full images (3:1) or icon and text with customisable colours.
