### ISSUE TITLE
forms in apps.fyne.io

### ISSUE THREAD

**Issue by ghost** [fyne-io/apps.fyne.io#44]
Hi all.

Something I noticed is that apps.fyne.io uses a form from a third party service, something like Zoho Forms. An alternative to a third-party service (in this case: Zoho Forms) is to use the GitHub API to send and receive pull requests from a contact form. Projects like [freeStuffDev](https://freestuff.dev/), have a contact form that is updated via pull request.

#### 1.1 Proof 1
![image](https://user-images.githubusercontent.com/111701513/204940245-26fd7cd8-aaa0-47c4-bcf3-237151894cec.png)

#### 1.2 Proof 2
![image](https://user-images.githubusercontent.com/111701513/204940433-265e9601-5f17-4d0e-b867-d417ee2c05b2.png)

#### 2. End-Concept
![image](https://user-images.githubusercontent.com/111701513/204940778-c1f9fa9b-6246-42d4-8b91-60428082f782.png)

**image-description:** As we can see in this image there is an API that connects to GitHub when the developer submits the form without Zoho Forms.

**Comment by andydotxyz** [comment]
This would be nice.
Can it be done with a static web site?

**Comment by andydotxyz** [comment]
> I believe so, but you need to be logged into GitHub first.

I guess if we were to add that to streamline things we would have to keep the old in place as well - people wanting to add their app could be coming from GitLab or other source hosting I would think...
