### ISSUE TITLE
cdn in apps.fyne.io

### ISSUE THREAD

**Issue by codehangen** [fyne-io/apps.fyne.io#45]
Hi all.

*Have you all ever thought about developing a cdn (content delivery network) for visual components of fyne.io?*

**Comment by andydotxyz** [comment]
Maybe outline what the benefit would be?
We already deliver as a static site through GitHub pages - their infrastructure is pretty solid

**Comment by andydotxyz** [comment]
Maybe I misunderstood. Perhaps this issue is on the wrong repository? Does it relate to the https://apps.fyne.io web site?

**Comment by andydotxyz** [comment]
Do you mean like https://addons.fyne.io?

**Comment by andydotxyz** [comment]
Cool
