### ISSUE TITLE
Category drop-down not scrollable on mobile

### ISSUE THREAD

**Issue by Jacalz** [fyne-io/apps.fyne.io#52]
The drop-down to select different categories it not scrollable on mobile (at least not on iOS). See image below:
![IMG_9978](https://user-images.githubusercontent.com/25466657/235375313-8562e8b6-5461-44cb-9c20-0d70be5f6ffc.png)

**Comment by andydotxyz** [comment]
Seems like a known issue with web flow (what the app was exported from) https://discourse.webflow.com/t/tutorial-make-mobile-menu-scrollable/28917.

Not sure how to start debugging on the iPhone web browser sadly!
